name: Publish Website institut-juno.de
on:
  push:
    branches: [ main ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.JUNO_FTP_HOSTNAME }}
          username: ${{ secrets.JUNO_FTP_USERNAME }}
          password: ${{ secrets.JUNO_FTP_PASSWORD }}
          server-dir: ./relaunch
          protocol: ftps
